### ISSUE TITLE
Icons do not work (Support library 25.3.0)

### ISSUE THREAD

**Issue by MFlisar** [andrewlord1990/SnackbarBuilder#28]
I tried something like following:

    public static void showInfo(ViewDataBinding binding, int info, int duration)
    {
        new SnackbarBuilder(binding.getRoot())
                .message(info)
                .icon(new IconicsDrawable(binding.getRoot().getContext())
                        .sizeDp(36)
                        .paddingDp(8)
                        .icon(GoogleMaterial.Icon.gmd_info)
                .color(Color.WHITE))
                .duration(duration)
                .build()
                .show();
    }

This fails with following exception:

	 java.lang.ClassCastException: android.widget.LinearLayout$LayoutParams cannot be cast to android.widget.FrameLayout$LayoutParams
		at android.widget.FrameLayout.onMeasure(FrameLayout.java:186)
		at android.support.design.widget.Snackbar$SnackbarLayout.onMeasure(Snackbar.java:335)
		at android.view.View.measure(View.java:21045)
		at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
		at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
		at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
		at android.view.View.measure(View.java:21045)
		at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
		at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
		at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
		at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
		at android.view.View.measure(View.java:21045)
		at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
		at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
		at android.view.View.measure(View.java:21045)
		at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
		at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1464)
		at android.widget.LinearLayout.measureVertical(LinearLayout.java:758)
		at android.widget.LinearLayout.onMeasure(LinearLayout.java:640)
		at android.view.View.measure(View.java:21045)
		at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6459)
		at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
		at com.android.internal.policy.DecorView.onMeasure(DecorView.java:849)
		at android.view.View.measure(View.java:21045)
		at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2569)
		at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1628)
		at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:1879)
		at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1508)
		at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7084)
		at android.view.Choreographer$CallbackRecord.run(Choreographer.java:927)
		at android.view.Choreographer.doCallbacks(Choreographer.java:702)
		at android.view.Choreographer.doFrame(Choreographer.java:638)
		at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:913)
		at android.os.Handler.handleCallback(Handler.java:751)
		at android.os.Handler.dispatchMessage(Handler.java:95)
		at android.os.Looper.loop(Looper.java:154)
		at android.app.ActivityThread.main(ActivityThread.java:6682)
		at java.lang.reflect.Method.invoke(Native Method)
		at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1520)
		at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1410)

My solution is to adjust the `SnackbarIconBuilder` to following:

	class SnackbarIconBuilder {

	  Snackbar snackbar;
	  private ImageView iconView;
	  private Drawable icon;
	  private int iconMarginStartPixels;
	  private int iconMarginEndPixels;

	  SnackbarIconBuilder(Snackbar snackbar) {
		this.snackbar = snackbar;
		iconView = (ImageView) snackbar.getView().findViewById(R.id.snackbarbuilder_icon);
	  }

	  static SnackbarIconBuilder builder(Snackbar snackbar) {
		return new SnackbarIconBuilder(snackbar);
	  }

	  SnackbarIconBuilder icon(Drawable icon) {
		this.icon = icon;
		return this;
	  }

	  SnackbarIconBuilder iconMarginStartPixels(int iconMarginStartPixels) {
		this.iconMarginStartPixels = iconMarginStartPixels;
		return this;
	  }

	  SnackbarIconBuilder iconMarginEndPixels(int iconMarginEndPixels) {
		this.iconMarginEndPixels = iconMarginEndPixels;
		return this;
	  }

	  ImageView bindToSnackbar() {

		SnackbarLayout view = (SnackbarLayout) snackbar.getView();
		TextView textView = (TextView)view.findViewById(android.support.design.R.id.snackbar_text);
		textView.setCompoundDrawablesWithIntrinsicBounds(icon, null, null, null);
                textView.setGravity(Gravity.CENTER_VERTICAL);
		return iconView;
	  }
	}

But this way, you loose the ability to set custom margins, although, in my case, that's no problem, I'm using iconics drawables where I can set some padding when creating the drawables...

Alternatively, you can remove the TextView from it's parent (which seems to have been a `LinearLayout` but is a `FrameLayout` now) and wrap it in a new `LinearLayout` and add the icon to this layout and then put the `LinearLayout` in place of the original one, have not tried it, but probably this works as well..

**Comment by andrewlord1990** [comment]
I will have a look tonight, i will update the library for latest version of
support libs.

It would be nice to keep the margins if
possible, but the icons are more important!

**Comment by andrewlord1990** [comment]
@MFlisar I wasn't aware of this change in the support design library until you created this issue. As you said, they have switched the LinearLayout for a FrameLayout. I'm not keen on having code replacing the layouts as it will make this part of the library heavily dependent on the underlying implementation. Therefore, I think I will be removing the icon support from the library. You will still be able to add an icon by yourself, using the compound drawable approach. This won't be compatible with appcompat vector drawables though.

Also, having an icon on a Snackbar isn't part of the Material Design spec and so I probably shouldn't have added it to the library in the first place.

**Comment by MFlisar** [comment]
I would not remove the icon support. It's just a few lines of code and people can decide theirself to not use it. I actually just use error or warning icons mostly to distinguish between info snackbars and others and I think it's much better with icons even if this is not material design...

**Comment by andrewlord1990** [comment]
@MFlisar The problem is that the icons don't work anymore. I guess I can implement icon support using compound drawable, but put a disclaimer that appcompat vector drawables don't work. Its a shame, but I don't want to start altering the view structure of the Snackbar. My reason for suggesting removing it is that it isn't "just a few lines of code", as when they alter the Snackbar as they have hear, the library breaks and needs fixing. Whereas all the other features of the library don't have such a large problem like this.

**Comment by MFlisar** [comment]
I understand you. Still I think it's not very likely that the TextView will be changed at any time. If you ask me, I would at least support it for now via the compund drawable solution I posted above ;-).

**Comment by andrewlord1990** [comment]
Yeah I do understand, I didn't really want a partial solution, but I understand. Will look into implementing this today and get a new version out for you to use. Will try to make it in a way that means it won't crash if they mess with the layout again. Thanks!

**Comment by MFlisar** [comment]
It's up to you to drop the support, I've forked the library anyway and can use my fork as well ;-)

**Comment by andrewlord1990** [comment]
Fair point, would rather if those interested in using the library are actually able to continue doing so! Will implement it asap.

**Comment by andrewlord1990** [comment]
Fixed.
